baseURL = "https://www.nicecorn.com"
DefaultContentLanguage = "zh-hant" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-hant"
title = "Corn Park"
copyright = "Corn Huang"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

[params]
subtitle = "玉之米的自留地"
favicon = "/av.png"
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = false
enableTwitterCards = false
title = "Corn Park" # will set 'og:site_name'
description = "玉之米的自留地"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/posts"
name = "歸檔"
weight = 1
# [[menu.main]]
# url = "/categories"
# name = "分類"
# weight = 2
[[menu.main]]
url = "/tags"
name = "標簽"
weight = 3
[[menu.main]]
url = "/about"
name = "关于"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 5